#
# test build and publish will be run on every release
#
# Created July 9th, 2022
# @author: ywarezk
# @version: 0.0.1
# @license: MIT
#

name: Build
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage/az-zoneless/cobertura-coverage.xml,./coverage/material-test/cobertura-coverage.xml # optional
          flags: unittests # optional
          name: az-zoneless # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - run: npm run build
      - run: cd dist/az-zoneless && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
